### ISSUE TITLE
GregorianToHijri not true

### ISSUE THREAD

**Issue by jebraili** [hubaishan/HijriDateLib#1]
hi, Gregorian To Hijri($year,$month,$da3) not true for example Gregorian date "2018-10-23" is "1440/02/13" hijri date  but this function returned "1440/02/14".
why this happened??

**Comment by hubaishan** [comment]
the Calendar class uses Um AlQura algorithm by default
"2018-10-23" is "1440/02/14" in Um AlQura algorithm 
in tabular algorithm (default Windows hijri calendar) it is "1440/02/13" 

to use tabular algorithm construct hijri\calendar as
`$h = new hijri\Calendar(['umalqura' => false]);`
